// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The spec's three presence states, and a fourth for anything else a server
 * sends — which the UI draws as nothing rather than guessing.
 */
export type Availability = "online" | "unavailable" | "offline" | "unknown";
