// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CallCredentials = { 
/**
 * WebSocket URL of the SFU, e.g. `wss://livekit.example.org`.
 */
livekitUrl: string, 
/**
 * Room-scoped JWT for `livekit-client` to connect with.
 */
jwt: string, 
/**
 * The LiveKit room name — the Matrix room ID, so every client agrees.
 */
alias: string, roomId: string, };
