// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaInfo } from "./MediaInfo";

/**
 * Message content, flattened into what the UI actually needs to draw.
 */
export type Content = { "kind": "text", body: string, formatted: string | null, } | { "kind": "emote", body: string, formatted: string | null, } | { "kind": "notice", body: string, formatted: string | null, } | { "kind": "image", body: string, media: MediaInfo, } | { "kind": "video", body: string, media: MediaInfo, } | { "kind": "audio", body: string, media: MediaInfo, } | { "kind": "file", body: string, media: MediaInfo, } | { "kind": "location", body: string, geoUri: string, } | { "kind": "sticker", body: string, media: MediaInfo, } | { "kind": "poll", question: string, answers: Array<string>, ended: boolean, } | { "kind": "redacted" } | { "kind": "unableToDecrypt", reason: string, } | { "kind": "membership", change: string, userId: string, displayName: string | null, } | { "kind": "profileChange", summary: string, } | { "kind": "state", eventType: string, stateKey: string, summary: string, } | { "kind": "callInvite" } | { "kind": "rtcNotification", intent: string | null, } | { "kind": "unsupported", eventType: string, };
