// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceInfo = { deviceId: string, displayName: string | null, isVerified: boolean, 
/**
 * True for the device this app is running as — it can't verify itself.
 */
isCurrent: boolean, firstSeen: number, };
