// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `VectorDiff` rendered for JS. Mirrors `eyeball_im::VectorDiff` so the
 * frontend can apply updates in place instead of re-rendering the world.
 */
export type Diff<T> = { "op": "append", values: Array<T>, } | { "op": "clear" } | { "op": "pushFront", value: T, } | { "op": "pushBack", value: T, } | { "op": "popFront" } | { "op": "popBack" } | { "op": "insert", index: number, value: T, } | { "op": "set", index: number, value: T, } | { "op": "remove", index: number, } | { "op": "truncate", length: number, } | { "op": "reset", values: Array<T>, };
