// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One custom emote the composer can substitute into an outgoing message.
 */
export type EmoteRef = { 
/**
 * Without the surrounding colons.
 */
shortcode: string, url: string, };
