// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stable, machine-readable discriminant for the frontend.
 */
export type ErrorKind = "not_signed_in" | "auth" | "unknown_room" | "no_timeline" | "matrix" | "bad_id" | "client_build" | "timeline" | "room_list" | "io" | "json" | "http" | "other";
