// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Content } from "./Content";
import type { Reaction } from "./Reaction";
import type { ReplyInfo } from "./ReplyInfo";
import type { SendState } from "./SendState";
import type { Shield } from "./Shield";
import type { ThreadSummary } from "./ThreadSummary";

export type EventItem = { eventId: string | null, transactionId: string | null, sender: string, senderName: string | null, senderAvatar: string | null, timestamp: number, isOwn: boolean, isEditable: boolean, canReply: boolean, isHighlighted: boolean, isEdited: boolean, 
/**
 * True when the body is nothing but emoji — the design renders those big.
 */
isEmojiOnly: boolean, sendState: SendState | null, shield: Shield | null, content: Content, reactions: Array<Reaction>, reply: ReplyInfo | null, threadRoot: string | null, threadSummary: ThreadSummary | null, readReceipts: Array<string>, };
