// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SsoProvider } from "./SsoProvider";

export type HomeserverInfo = { serverName: string, homeserverUrl: string, supportsPassword: boolean, supportsSso: boolean, ssoProviders: Array<SsoProvider>, 
/**
 * MatrixRTC focus advertised in the server's `.well-known`, if any.
 */
livekitServiceUrl: string | null, };
