// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackImage } from "./PackImage";
import type { PackSource } from "./PackSource";

export type ImagePack = { 
/**
 * Stable across reloads, and what the frontend uses to address a pack:
 * `user` for the personal one, `<room_id>|<state_key>` for a room's.
 */
id: string, source: PackSource, roomId: string | null, stateKey: string | null, displayName: string, avatarUrl: string | null, attribution: string | null, images: Array<PackImage>, 
/**
 * Whether this pack is carried outside the room it belongs to — the
 * `m.image_pack.rooms` list. Always true for the MSC's personal pack,
 * which is account data and so has no room to be outside of.
 *
 * Not a filter: everything returned here is usable where it was asked for,
 * including a room's own packs in that room. This says whether it follows
 * you elsewhere, which is what the settings toggle writes.
 */
everywhere: boolean, 
/**
 * Whether this account may write the pack back.
 */
canEdit: boolean, };
