// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LatestRelease = { version: string, notes: string, 
/**
 * The release page, not an asset: which asset is right depends on a
 * platform question the browser is better placed to answer than we are.
 */
url: string, };
