// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaInfo = { mxc: string | null, mimetype: string | null, size: number | null, width: number | null, height: number | null, durationMs: number | null, blurhash: string | null, thumbnailMxc: string | null, 
/**
 * Voice-message amplitude samples, when present.
 */
waveform: Array<number> | null, isVoice: boolean, };
