// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the create-room dialog collects.
 */
export type NewRoom = { name: string, topic?: string | null, 
/**
 * Anyone can find and join it, and it gets listed in the directory.
 */
isPublic?: boolean, 
/**
 * Alias localpart for a public room — `movies`, not `#movies:server`.
 */
alias?: string | null, encrypted?: boolean, invite?: Array<string>, 
/**
 * The space to file it under, if one was open when the user hit create.
 */
parentSpace?: string | null, };
