// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewRoomResult = { roomId: string, 
/**
 * The room exists, but it couldn't be filed under the space. Not an error:
 * the room is real and usable, it's just loose.
 */
spaceWarning: string | null, };
