// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend can ask us to publish about the user.
 */
export type OwnPresence = "online" | "unavailable" | "offline";
