// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a pack lives: account data, or a room's state.
 */
export type PackSource = "user" | "room";
