// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One change to a pack, applied on top of whatever the server currently has.
 *
 * Edits are described rather than sent as a whole pack because two clients
 * touching the same pack shouldn't be able to erase each other's images: every
 * one of these reads first, changes one thing, and writes back.
 */
export type PackEdit = { "kind": "putImage", shortcode: string, url: string, body?: string | null, isEmoticon: boolean, isSticker: boolean, width?: number | null, height?: number | null, size?: number | null, mimetype?: string | null, } | { "kind": "rename", from: string, to: string, } | { "kind": "removeImage", shortcode: string, } | { "kind": "setName", name: string, };
