// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackImage = { 
/**
 * The `:name:` a person types, without the colons.
 */
shortcode: string, url: string, 
/**
 * Alt text for the image. Falls back to the shortcode.
 */
body: string, isEmoticon: boolean, isSticker: boolean, width: number | null, height: number | null, size: number | null, mimetype: string | null, };
