// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which pack an edit is aimed at.
 *
 * The personal pack has no room; a room pack is a room plus a state key. The
 * frontend addresses packs by their `id`, and this is that id taken apart.
 */
export type PackTarget = { roomId?: string | null, stateKey?: string | null, };
