// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One item in the library, with a thumbnail small enough to hand to the
 * WebView inline.
 */
export type Photo = { id: string, 
/**
 * Videos get a duration badge and a longer export.
 */
video: boolean, seconds: number, 
/**
 * A `data:image/jpeg;base64,…` URI. Small enough to inline, and it avoids
 * a second round trip per tile just to fetch the image.
 */
thumb: string, };
