// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Presence } from "./Presence";

/**
 * A batch of changes, plus whether presence works here at all.
 */
export type PresenceUpdate = { users: Array<Presence>, 
/**
 * False once the server has refused every request in a round: the UI hides
 * its indicators rather than claiming everyone is offline.
 */
supported: boolean, };
