// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Availability } from "./Availability";

/**
 * One person's presence, as the UI draws it.
 */
export type Presence = { userId: string, presence: Availability, 
/**
 * The free-text status the *presence* system carries. Distinct from the
 * MSC4133 profile status in `profile.rs`, which is the one people set by
 * hand and the one the profile card shows.
 */
statusMsg: string | null, 
/**
 * When they were last active, as a unix timestamp in milliseconds.
 *
 * The server answers with an *age*, which stops being true the moment it
 * arrives, so it's turned into an absolute instant here — a "last seen"
 * label has to keep counting between polls.
 */
lastActive: number | null, 
/**
 * The server's own "they're actively doing something right now" flag.
 */
currentlyActive: boolean, };
