// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Profile = { userId: string, displayName: string | null, avatarUrl: string | null, 
/**
 * Commet's `chat.commet.profile_bio`, unwrapped from its `body` object.
 */
bio: string | null, 
/**
 * Commet's `chat.commet.profile_status`.
 */
status: string | null, 
/**
 * `gg.uwu.cover_url` — ours; no other client reads it.
 */
coverUrl: string | null, };
