// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A partial update. `None` leaves a field alone; `Some("")` clears it.
 */
export type ProfileUpdate = { bio?: string | null, status?: string | null, coverUrl?: string | null, };
