// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Reaction = { key: string, count: number, 
/**
 * True when the local user is one of the senders.
 */
mine: boolean, 
/**
 * True while our own reaction is still in flight.
 */
pending: boolean, senders: Array<string>, };
