// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Photo } from "./Photo";

export type RecentPhotos = { 
/**
 * False where there is no library to read — every desktop platform.
 */
supported: boolean, 
/**
 * True when the user granted access to *some* photos. Not an error: the
 * list is what they chose to share, and the UI offers a way to widen it.
 */
limited: boolean, 
/**
 * True when access was refused outright, so the UI can say so rather than
 * showing an empty grid that looks broken.
 */
denied: boolean, photos: Array<Photo>, };
