// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecoveryState } from "./RecoveryState";

export type RecoveryStatus = { state: RecoveryState, backupExists: boolean, crossSigningReady: boolean, };
