// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The SDK's `RecoveryState`, which isn't `Serialize`.
 */
export type RecoveryState = "enabled" | "disabled" | "incomplete" | "unknown";
