// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the account stands with a room.
 */
export type RoomMembership = "joined" | "invited" | "left" | "knocked" | "banned";
