// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verification } from "./Verification";

export type RoomMember = { userId: string, displayName: string | null, avatarUrl: string | null, powerLevel: number, 
/**
 * `join` | `invite` | `leave` | `ban` | `knock` | `unknown` — the event's
 * own spelling, not `RoomMembership`'s.
 */
membership: string, isIgnored: boolean, verification: Verification, };
