// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatestEvent } from "./LatestEvent";
import type { RoomMembership } from "./RoomMembership";

export type RoomSummary = { id: string, name: string, topic: string | null, canonicalAlias: string | null, avatarUrl: string | null, isDirect: boolean, 
/**
 * The other person, when a DM has exactly one of them — what a presence
 * dot in the sidebar hangs off. `None` for group rooms, and for "direct"
 * rooms with any number of members other than one, which the flag allows.
 */
dmUserId: string | null, isEncrypted: boolean, isSpace: boolean, 
/**
 * A room that isn't a conversation — a pack room, or anything else with a
 * room type we don't draw. Spaces have their own flag and their own rail.
 */
isUtility: boolean, isFavourite: boolean, isLowPriority: boolean, isMuted: boolean, membership: RoomMembership, notificationCount: number, highlightCount: number, hasUnread: boolean, isMarkedUnread: boolean, memberCount: number, latest: LatestEvent | null, 
/**
 * Server-side recency stamp, used to order the list.
 */
recency: number, 
/**
 * Space IDs this room is a child of.
 */
parentSpaces: Array<string>, 
/**
 * True while a MatrixRTC session is live in this room.
 */
hasActiveCall: boolean, 
/**
 * An MSC3417 video room — a call you join, not a text room.
 */
isVideoRoom: boolean, };
