// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSummary } from "./RoomSummary";

/**
 * The room list as it stands, and the last batch folded into it.
 */
export type RoomsSnapshot = { seq: number, rooms: Array<RoomSummary>, };
