// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What this account is allowed to change about a room.
 *
 * Read once when the room panel opens rather than carried on every summary:
 * it needs the power-level state event, and the answer only matters for the
 * room you're looking at.
 */
export type RoomPermissions = { canRename: boolean, canSetTopic: boolean, canInvite: boolean, };
