// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diff } from "./Diff";
import type { RoomSummary } from "./RoomSummary";

/**
 * A batch of room-list changes, numbered so the frontend can tell whether a
 * snapshot it holds already includes them.
 */
export type RoomsUpdate = { seq: number, diffs: Array<Diff<RoomSummary>>, };
