// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `SasState`, without the payloads.
 */
export type SasStage = "created" | "started" | "accepted" | "keysExchanged" | "confirmed" | "done" | "cancelled";
