// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SasEmoji } from "./SasEmoji";
import type { SasStage } from "./SasStage";

export type SasStateInfo = { flowId: string, otherUserId: string, state: SasStage, 
/**
 * The seven SAS emoji, once both sides have exchanged keys.
 */
emoji: Array<SasEmoji> | null, decimals: [number, number, number] | null, cancelReason: string | null, cancelledByUs: boolean | null, cancelCode: string | null, };
