// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmoteRef } from "./EmoteRef";

export type SendOptions = { body: string, 
/**
 * Rendered as Markdown when true; the design's composer sends plain text
 * unless the user opts in.
 */
markdown?: boolean, replyTo?: string | null, threadRoot?: string | null, 
/**
 * `m.text` (default), `m.emote`, `m.notice`
 */
msgtype?: string | null, 
/**
 * Custom emotes the body might mention, as `:shortcode:`.
 *
 * The composer sends the whole set it knows about rather than deciding
 * what's in the text; matching is done once, against the rendered HTML, so
 * Markdown and emotes can both survive in one message.
 */
emotes?: Array<EmoteRef>, };
