// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendState = { "status": "notSentYet", progress: number | null, } | { "status": "failed", error: string, isRecoverable: boolean, } | { "status": "sent", eventId: string, };
