// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionInfo = { userId: string, deviceId: string, homeserver: string, displayName: string | null, avatarUrl: string | null, 
/**
 * True when secrets had to be written to a file because the OS keychain
 * was unavailable. The UI warns about this rather than hiding it.
 */
insecureStorage: boolean, };
