// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A room both of you are in, reduced to what a profile card draws.
 */
export type SharedRoom = { id: string, name: string, avatarUrl: string | null, isSpace: boolean, isDirect: boolean, };
