// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShieldColour } from "./ShieldColour";

export type Shield = { colour: ShieldColour, message: string, };
