// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpaceSummary = { id: string, name: string, avatarUrl: string | null, children: Array<string>, notificationCount: number, highlightCount: number, };
