// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One image from a pack, on its way out as an `m.sticker`.
 */
export type StickerOptions = { 
/**
 * Alt text — the shortcode, unless the pack gave the image a body.
 */
body: string, url: string, width?: number | null, height?: number | null, size?: number | null, mimetype?: string | null, };
