// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `matrix_sdk_ui::sync_service::State`, without the payloads.
 */
export type SyncState = "idle" | "running" | "terminated" | "error" | "offline";
