// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kind of row a `TimelineItemDto` is. Not the SDK's `TimelineItemKind`,
 * which carries the payloads.
 */
export type TimelineRowKind = "event" | "dateDivider" | "readMarker" | "timelineStart";
