// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventItem } from "./EventItem";
import type { TimelineRowKind } from "./TimelineRowKind";

/**
 * One row of the timeline. `kind` discriminates; only the matching payload is
 * populated.
 */
export type TimelineItem = { 
/**
 * Stable identity for React keys and for diff application.
 */
id: string, kind: TimelineRowKind, timestamp?: number, event?: EventItem, };
