// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diff } from "./Diff";
import type { TimelineItem } from "./TimelineItem";

export type TimelineUpdate = { 
/**
 * Room ID, or `<roomId>|<threadRoot>` for a thread — `timeline::timeline_key`.
 */
roomId: string, diffs: Array<Diff<TimelineItem>>, };
