// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypingUser } from "./TypingUser";

export type TypingUpdate = { roomId: string, users: Array<TypingUser>, };
