// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedRoom } from "./SharedRoom";
import type { Verification } from "./Verification";

/**
 * The parts of a profile card that come from our own client rather than from
 * the profile endpoint: whether we've verified them, whether there's already a
 * DM, and where the two of you overlap.
 */
export type UserContext = { userId: string, isMe: boolean, verification: Verification, dmRoomId: string | null, sharedRooms: Array<SharedRoom>, };
