// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * What an `Error` looks like once it reaches the frontend.
 */
export type UwuError = { kind: ErrorKind, message: string, };
