// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether we've verified someone's identity via cross-signing.
 */
export type Verification = "verified" | "unverified" | "unknown";
