// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestState } from "./RequestState";

export type VerificationRequestInfo = { flowId: string, otherUserId: string, otherDeviceId: string | null, isSelfVerification: boolean, weStarted: boolean, state: RequestState, 
/**
 * Why the flow ended, when it ended badly and before SAS ever started —
 * otherwise there is nothing to show the user but "it stopped".
 */
cancelReason: string | null, 
/**
 * Which side sent the cancel. Without this the UI has to guess, and it
 * guessed wrong in the direction that matters: `m.user` reads as "the
 * user cancelled", which a reader takes to mean *them*, when half the
 * time it was this device.
 */
cancelledByUs: boolean | null, 
/**
 * The spec code (`m.user`, `m.timeout`, `m.unknown_method`, …). The
 * human-readable reason collapses distinct failures into similar
 * sentences; the code is what makes a bug report actionable.
 */
cancelCode: string | null, };
