// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the native side can see about this WebView's WebRTC support.
 *
 * The frontend asks for this only after `RTCPeerConnection` has turned out to
 * be missing, and turns it into a sentence that names the actual cause instead
 * of livekit's "your browser doesn't support this".
 */
export type WebrtcDiagnosis = { 
/**
 * `enable-webrtc` as WebKitGTK reported it back *after* we set it.
 *
 * Worth reporting, worth nothing on its own: where WebRTC is compiled out
 * the property is a stub that stores whatever it is given, so this reads
 * back `true` on a WebKitGTK that has no WebRTC in it at all. Only a
 * `false` here says anything — that the setter didn't even take.
 */
settingEnabled: boolean, 
/**
 * Same, for `enable-media-stream` — the one that puts `mediaDevices` on
 * `navigator`.
 */
mediaStreamEnabled: boolean, 
/**
 * WebKitGTK's runtime version, e.g. `2.44.3`. `set_enable_webrtc` only
 * exists from 2.38, and the GStreamer WebRTC backend only became usable
 * around 2.40.
 */
webkitVersion: string, 
/**
 * Is `libgstwebrtc.so` (gst-plugins-bad) installed? WebKitGTK's backend is
 * `webrtcbin`, and without it `RTCPeerConnection` stays hidden however the
 * settings read back.
 */
gstWebrtc: boolean, 
/**
 * Is `libgstnice.so` (gstreamer1.0-nice) installed? That's ICE; without it
 * a connection can be created but never gathers a candidate.
 */
gstNice: boolean, 
/**
 * Running from an AppImage, which carries its own WebKitGTK — so the
 * version above is that one, not whatever the distribution installed.
 */
appimage: boolean, };
