// Regenerate src/lib/bindings from the Rust wire types.
//
// ts-rs writes one file per type as a side effect of its export tests. The
// directory is emptied first so a type deleted in Rust disappears here too,
// rather than lingering as a file nothing regenerates — and the barrel is
// rebuilt from whatever was actually written.

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "src/lib/bindings");

fs.rmSync(out, { recursive: true, force: true });

// Run from the repo root so cargo finds `.cargo/config.toml`, which is what
// points ts-rs at `out` and keeps u64 a `number`.
execFileSync(
  "cargo",
  ["test", "--manifest-path", "src-tauri/Cargo.toml", "--lib", "export_bindings"],
  { cwd: root, stdio: "inherit" },
);

const types = fs
  .readdirSync(out)
  .filter((file) => file.endsWith(".ts"))
  .map((file) => file.slice(0, -".ts".length))
  .sort();

fs.writeFileSync(
  path.join(out, "index.ts"),
  "// Generated by scripts/bindings.mjs. Do not edit by hand.\n\n" +
    types.map((name) => `export type * from "./${name}";\n`).join(""),
);

console.log(`\n${types.length} types in src/lib/bindings`);
